<option value="#3 NBA Jam - SNES - Race">#3 NBA Jam - SNES - Race</option>
<option value="#6 - Yoshi's Island - SNES - Score Attack">#6 - Yoshi's Island - SNES - Score Attack</option>
<option value="#7 - Sonic Advance - GBA - Score Attack">#7 - Sonic Advance - GBA - Score Attack</option>
<option value="#8 F-Zero - SNES - Race">#8 F-Zero - SNES - Race</option>
<option value="#9 -Rocket Knight Adventures - SNES - Race">#9 -Rocket Knight Adventures - SNES - Race</option>
<option value="#10 - Super Mario Bros. - NES - Distance">#10 - Super Mario Bros. - NES - Distance</option>
<option value="#12 - Kirby: Nightmare in Dreamland - GBA - Race">#12 - Kirby: Nightmare in Dreamland - GBA - Race</option>
<option value="#13 - U N Squadron - SNES - Score Attack">#13 - U N Squadron - SNES - Score Attack</option>
<option value="#17 - Kirby Super Star - SNES  - Score Attack">#17 - Kirby Super Star - SNES  - Score Attack</option>
<option value="#18 - Kirby: Nightmare in Dreamland - GBA - Race">#18 - Kirby: Nightmare in Dreamland - GBA - Race</option>
<option value="#20 - Super Mario Bros. 2 (All-Stars Edition) - SNES -  Distance">#20 - Super Mario Bros. 2 (All-Stars Edition) - SNES -  Distance</option>
<option value="#21 - Kirby's Adventure - NES - Race">#21 - Kirby's Adventure - NES - Race</option>
<option value="#22 - Sonic the Hedgehog 2 - GEN - Race">#22 - Sonic the Hedgehog 2 - GEN - Race</option>
<option value="#23 - Mega Man - NES - Race">#23 - Mega Man - NES - Race</option>
<option value="#24 - Xevious - NES - Score Attack">#24 - Xevious - NES - Score Attack</option>
<option value="#26 - Bubble Bobble - NES - Distance">#26 - Bubble Bobble - NES - Distance</option>
<option value="#27 - Rockman 3 Endless - NES - Score Attack">#27 - Rockman 3 Endless - NES - Score Attack</option>
<option value="#30 - Tiny Toon Adventures: Buster Busts Loose! -  SNES - Distance">#30 - Tiny Toon Adventures: Buster Busts Loose! -  SNES - Distance</option>
<option value="#34 - Mega Man 3 - NES - Score Attack">#34 - Mega Man 3 - NES - Score Attack</option>
<option value="#41 - Kuru Kuru Kururin - GBA - Distance">#41 - Kuru Kuru Kururin - GBA - Distance</option>
<option value="#42 - Revolution X - SNES - Score Attack">#42 - Revolution X - SNES - Score Attack</option>
<option value="#43 - Mega Man 3 - NES - Race">#43 - Mega Man 3 - NES - Race</option>
<option value="#45 - Chip N' Dale's Rescue Rangers - NES - Race">#45 - Chip N' Dale's Rescue Rangers - NES - Race</option>
<option value="#48 - Ducktales 2 - NES - Race">#48 - Ducktales 2 - NES - Race</option>
<option value="#49 - Kirby and the Amazing Mirror - GBA - Race">#49 - Kirby and the Amazing Mirror - GBA - Race</option>
<option value="#50 - Super Mario Kart - SNES - Score Attack">#50 - Super Mario Kart - SNES - Score Attack</option>
<option value="#52 - Magical Puzzle Popilis - GG - Distance">#52 - Magical Puzzle Popilis - GG - Distance</option>
<option value="#53 - Super Mario Bros. Deluxe - GBC - Score Attack">#53 - Super Mario Bros. Deluxe - GBC - Score Attack</option>
<option value="#54 - Ninja Gaiden - NES - Score Attack">#54 - Ninja Gaiden - NES - Score Attack</option>
<option value="#55 - Streets of Rage 2 - GEN - Distance">#55 - Streets of Rage 2 - GEN - Distance</option>
<option value="#57 - Kirby Super Star - SNES - Score Attack">#57 - Kirby Super Star - SNES - Score Attack</option>
<option value="#58 - Pac-Man 2: The New Adventures - SNES - Other">#58 - Pac-Man 2: The New Adventures - SNES - Other</option>
<option value="#59 - Sonic Advance 3 - GBA - Race">#59 - Sonic Advance 3 - GBA - Race</option>
<option value="#60 - Cool Spot - SNES - Score Attack">#60 - Cool Spot - SNES - Score Attack</option>
<option value="#61 - Bubsy - SNES -Distance">#61 - Bubsy - SNES -Distance</option>
<option value="#62 - That's So Raven  - GBA - Race">#62 - That's So Raven  - GBA - Race</option>
<option value="#64 - Super Metroid  - SNES - Race">#64 - Super Metroid  - SNES - Race</option>
